### ISSUE TITLE
how can i setup the key schema for this connector

### ISSUE THREAD

**Issue by iswarezwp** [jcustenborder/kafka-connect-cassandra#11]
hello,  i test this connector like the following:
 ```
bin/kafka-console-producer.sh \
  --broker-list localhost:9092 \
 --property "parse.key=true" \
 --property "key.separator=:" \
  --property key.schema='{"type":"record", "fields":[{"name":"id","type":"int"}]}' \
  --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"id","type":"int"},{"name":"product", "type": "string"}, {"name":"quantity", "type": "int"}, {"name":"price", "type": "float"}]}' \
  --topic test_topic

1:{"id": 1, "product": "aaa", "quantity": 12, "price": 12.5}
```

but got errors:
```
[2018-04-07 15:44:12,125] WARN build() - Schemaless mode detected. Cannot generate DDL so assuming table is correct. (com.github.jcustenborder.kafka.connect.cassandra.ConnectSchemaBuilder:164)
[2018-04-07 15:44:12,188] INFO Using data-center name 'my_data_center' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor) (com.datastax.driver.core.policies.DCAwareRoundRobinPolicy:95)
[2018-04-07 15:44:12,188] INFO New Cassandra host /192.168.70.102:9042 added (com.datastax.driver.core.Cluster:1568)
[2018-04-07 15:44:12,189] INFO New Cassandra host /192.168.70.103:9042 added (com.datastax.driver.core.Cluster:1568)
[2018-04-07 15:44:12,189] INFO New Cassandra host /192.168.70.101:9042 added (com.datastax.driver.core.Cluster:1568)
[2018-04-07 15:44:12,189] ERROR Task sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:404)
java.lang.NullPointerException
	at com.github.jcustenborder.kafka.connect.cassandra.ConnectSchemaBuilder.create(ConnectSchemaBuilder.java:181)
	at com.github.jcustenborder.kafka.connect.cassandra.ConnectSchemaBuilder.build(ConnectSchemaBuilder.java:174)
	at com.github.jcustenborder.kafka.connect.cassandra.CassandraSessionImpl.ensureTable(CassandraSessionImpl.java:69)
	at com.github.jcustenborder.kafka.connect.cassandra.CassandraSinkTask.put(CassandraSinkTask.java:94)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:384)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:240)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2018-04-07 15:44:12,189] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask:405)
```

I check the code, this exception shows that the keySchema  is null.

How can I send a correct keySchema (maybe the valueSchema also) ?

**Comment by jcustenborder** [comment]
@iswarezwp Try this:
`{"id": 1}:{"id": 1, "product": "aaa", "quantity": 12, "price": 12.5}`
